name: ${ENV_PROJECT_NAME}

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: ${ENV_MODE}
    env_file:
      - .env
    volumes:
      - ./src:/app/src

  tester:
    profiles:
      - testing
    build:
      context: .
      dockerfile: Dockerfile
      target: testing
    env_file:
      - .env
    volumes:
      - ./src:/app/src
      - ./tests:/app/tests
